### ISSUE TITLE
Catch case where clang-format is not found/installed

### ISSUE THREAD

**Issue by masmiley** [rat-pac/ratpac-two#108]
The new autoformatting feature assumes that clang-format will be present on the system, when that's not necessarily the case. We should add something to catch that case instead of seeing the generic `command not found` error message. The message does not prevent the formatting script from completing and just means it will do nothing over than print the message to the screen for each file, so it is not particularly urgent and could wait until a new round of build-related revisions.

**Comment by tannerbk** [comment]
Should be fixed, can you confirm?

**Comment by JamesJieranShen** [comment]
I believe this is completed. Feel free to re-open if needed.
